# Generated by Django 5.2.8 on 2025-11-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="sum_payment_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Id суммы платежа"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="sum_payment",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Сумма платежа"
            ),
        ),
    ]
