# Generated by Django 5.2.8 on 2025-11-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_link_payment_sum_payment_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="sum_payment_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Id сессии"
            ),
        ),
    ]
