# Generated by Django 5.2.8 on 2025-11-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0003_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["name", "description", "price_course"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["name", "description", "courses", "price_lesson"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="price_course",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Цена курса"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price_lesson",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Цена урока"
            ),
        ),
    ]
