# Generated by Django 5.2.8 on 2025-11-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0004_alter_course_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["name", "description", "price"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["name", "description", "courses", "price"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.RenameField(
            model_name="course",
            old_name="price_course",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="price_lesson",
            new_name="price",
        ),
    ]
